name: Gofmt

on:
  pull_request:
    types: [open, reopened, edited]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Check lint
      run: go fmt .
