name: Gofmt

on:
  pull_request:
    types: [opened, reopened, edited]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - name: Check lint
      run: |
        format_output=$(gofmt -s -l .)
        echo "Files that do not match gofmt"
        echo "$format_output"
        if [ "$(echo "$format_output" | wc -l)" -gt 0 ]; then exit 1; fi
        exit 0
