name: Gofmt

on:
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - name: Check lint
      run: |
        format_output=$(gofmt -s -l .)
        if [ "$(echo "$format_output" | wc -l)" -gt 1 ]
        then
          echo "Files that do not match gofmt"
          echo "$format_output"
          exit 1
        else 
          echo "All files match gofmt"
          exit 0
        fi
        
